samples_tsv: /cluster/project/reddy/katja/NGS_pipeline/data/P3569_LUCA-TCRA3_KH157/P3569_LUCA-TCRA3_KH157_samples.tsv

singleton_dir: /cluster/project/reddy/katja/NGS_pipeline/data/P3569_LUCA-TCRA3_KH157/umi/27_04_2026_KH157
output_dir: /cluster/project/reddy/katja/NGS_pipeline/data/P3569_LUCA-TCRA3_KH157/umi/27_04_2026_KH157

wt_anchor: "CCTGGTGCCCGGCCCGAA"
var_len: 33
min_umis: 3

# how to map sample sheet → filenames
# script assumes singleton files are named like: <sample_id>_<sample_name>_singletons.fastq.gz
singleton_suffix: "_singletons.fastq.gz"
