quality_threshold: 20
min_length: 50
expected_length: 297
seq_threshold: 5
qtrim: "r"
fwd_adapter: "CGTAATTAGAGGCGATGAGGTG"
rc_adapter: "CCATACCGGGTGGTCGTG"
wt: "CGGCAGATCGCACCAGGCCAGACCGGTAAGATCGCTGACTACAACTATAAGCTGCCTGATGATTTTACAGGCTGCGTGATCGCCTGGAACTCTAACAACCTGGATAGCAAGGTGGGCGGCAACTACAACTACCTGTACCGGCTGTTTCGCAAGTCTAACCTGAAACCTTTCGAGAGAGACATCTCCACAGAGATCTACCAGGCCGGTTCTACACCTTGTAACGGGGTGGAAGGCTTCAACTGTTACTTCCCTCTGCAAAGCTACGGCTTCCAGCCTACCAATGGAGTCGGCTACCAG"
repair: true
trim: true
filter: true
input_dir: "/cluster/project/reddy/rakuhn/Test_123C_Library/fastq_files/Nanopore"
output_dir: "/cluster/project/reddy/rakuhn/Test_123C_Library/output_nanopore"
bbmap_dir: "/cluster/project/reddy/rakuhn/bbmap"