# Paths
processed_base_dir: "/cluster/project/reddy/katja/NGS_pipeline/data/P3408_LUCA-TCRA3/processed"
extracted_base_dir: "/cluster/project/reddy/katja/NGS_pipeline/data/P3408_LUCA/extracted/"
logs_dir: "/cluster/project/reddy/katja/NGS_pipeline/logs/P3408_LUCA-TCRA3"
sample_sheet: "/cluster/project/reddy/katja/NGS_pipeline/scripts/samples.tsv"

# Codon extraction settings
start_anchor: "CCTGGTGCCCGGCCCGAA"
end_anchor: "GCAAAGATA"
max_mismatches: 1
codons: 11

# Input FASTQ patterns
no_consensus: "*_combined_final.fastq.gz"
consensus: "umi/*_consensus_{consensus_mode}.fastq.gz"
