# ================= OUTPUT =================
output_dir: /cluster/project/reddy/katja/NGS_pipeline/data/P3481_LUCA-TCRDMF5/extracted


# ================= Anchor / extraction =================
anchor_sequence: "TCTGGTGCCTTGTCCAAA"

anchor_max_mismatches: 0
region_length_nt: 33


# ================= Filtering / outputs =================
drop_if_contains_N: true
write_fail_fastq: false
write_aa_tsv: true


# ================= Library validation =================
library_mode: 3xNNK   # combinatorial or 3xNNK

# ---- Combinatorial design codons (DESIGN ORIENTATION) ----
degenerate_codons:
  - "SCN"
  - "RGY"
  - "RGY"
  - "VNB"
  - "ARY"
  - "VNB"
  - "GYN"
  - "RRY"
  - "GRR"
  - "CWR"
  - "TWY"

# ---- 3xNNK specifics (only used if library_mode: 3xNNK) ----
WT_nt_33: "GCCAGCAGCCTAAGTTTCGGCACTGAAGCTTTC"

max_mutated_codons: 3


# ================= Sample-driven input =================

# Mapping from sample_id -> sample_name
samples_tsv: /cluster/project/reddy/katja/NGS_pipeline/scripts/P3481_LUCA-TCRDMF5_samples.tsv

# Folder containing processed FASTQs
input_dir: /cluster/project/reddy/katja/NGS_pipeline/data/P3481_LUCA-TCRDMF5/umi

# File endings to look for
# If one is empty ("") it will be skipped.
# If BOTH are empty -> script throws error.
# If suffix is set but file is missing -> error.

input_suffixes_consensus: "_consensus.fastq.gz"     # set "" to disable
input_suffixes_singletons: "_singletons_rescued.fastq.gz"   # set "" to disable
